item {
  id:1
  name:'bjt'
}
item {
  id:2
  name:'capacitor'
}
item {
  id:3
  name:'diode'
}
item {
  id:4
  name:'ground'
}
item {
  id:5
  name:'inductor'
}
item {
  id:6
  name:'opamp'
}
item {
  id:7
  name:'resistor'
}
item {
  id:8
  name:'sourceac'
}
item {
  id:9
  name:'sourcedc'
}
item {
  id:10
  name:'sourcevc'
}
